### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by AdamMcAdamson** [UTDNebula/nebula-api#102]
...I think we should talk about testing, since in my experience that has been instrumental in ensuring that all the components integrate well with each other.

_Originally posted by @ahshabbir in https://github.com/UTDNebula/nebula-api/pull/98#pullrequestreview-1062798704_

Initial discussions begin here:
https://github.com/UTDNebula/nebula-api/discussions/101

**Comment by tchan24** [comment]
Has anyone tried sending requests?

**Comment by AdamMcAdamson** [comment]
A seemingly useful resource for tackling this:
https://medium.com/rate-engineering/go-test-your-code-an-introduction-to-effective-testing-in-go-6e4f66f2c259

**Comment by ahshabbir** [comment]
Do we still want a blackbox integration test for the container? I'd imagine its not worth the dev time, since it would involve the following:

1. Spin up a mongo instance
2. Load it with data
3. (build?) and spin up a api container
4. Use dockertest to orchestrate everything and hit the endpoints, check the results

In addition, dockertest is really heavy duty, it takes a lot of resources and it only works with a docker daemon. I think instead we should close this issue and include this as the focus for the API redesign.

**Comment by jpahm** [comment]
I'd agree that a more lightweight approach is desired, and I think doing testing as planned in the API redesign is for the best.

That being said, I'd like to keep using this issue as the basis for testing discussion so that we have past context to work with.

**Comment by jpahm** [comment]
Closing this as not planned for now, will reference in a future testing issue.
