### ISSUE TITLE
Update OpenAPI spec and ensure that it matches existing API functionality

### ISSUE THREAD

**Issue by ahshabbir** [UTDNebula/nebula-api#195]
We already have an OpenAPI Spec written for our API, but we need to update it so that it matches all of the changes present in our API including the new models if they are integrated in the API. This also should be uploaded somewhere in our github. A couple of discussion questions:

1. Should we break the spec up into multiple files, then concatenate them once we need to complete one?
2. Should we host the API spec on some endpoint in the API so that anyone who wants to view the specification can do so easily?

Resources:
1. OpenAPi Specification v2: https://swagger.io/specification/v2/

I feel that this is a good L1 story because you don't really need to know how to code to write this; its a good exploratory story that will have you querying the endpoints and seeing what comes out and even reading some code to see how to API works.

**Comment by jasonappah** [comment]
(note that I don't have a lot of context here and am fairly OOTL wrt to API development/plans, so take this stuff with a grain of salt)

In my opinion, OpenAPI specs get really annoying to edit manually when they're in one massive file so I think it'd be best to use separate files and join them somehow. I feel like there has to be tooling out there that makes it easier to author a spec and join multiple files together, especially since the OpenAPI spec already supports [$refs that refer to fragments in remote files](https://swagger.io/docs/specification/using-ref/#syntax).

I don't see any reason why the OpenAPI spec shouldn't be public, and eventually it might be useful to generate docs from the spec too.

**Comment by jpahm** [comment]
> In my opinion, OpenAPI specs get really annoying to edit manually when they're in one massive file so I think it'd be best to use separate files and join them somehow. I feel like there has to be tooling out there that makes it easier to author a spec and join multiple files together, especially since the OpenAPI spec already supports [$refs that refer to fragments in remote files](https://swagger.io/docs/specification/using-ref/#syntax).
> 
> I don't see any reason why the OpenAPI spec shouldn't be public, and eventually it might be useful to generate docs from the spec too.

I agree that we should take advantage of the remote `$refs` capability (which, contrary to what the name seems to imply, actually lets you reference files on the same server). I also see no reason to not have the spec publicly available.

**Comment by KD-kAnEsHi** [comment]
Is this still open? It seems like its being about a year since this task has being out

**Comment by jpahm** [comment]
> Is this still open? It seems like its being about a year since this task has being out

Yes, this is still open! I can provide the current API spec for reference if you'd like to work on this.

**Comment by jpahm** [comment]
This has been closed via #215,
