### ISSUE TITLE
Aggregate courses via internal_course_number

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/nebula-api#223]
Currently, the aggregation of courses (particularly for the grades endpoint) is done via finding courses with the specified `subject_prefix` and `course_number` attributes and then performing operations on them accordingly, such as finding their associated `sections` and aggregating their `grade_distribution`s together.

However, this is a flawed system that does not properly take into account course versioning; courses do not necessarily maintain the same prefixes or numbers over time -- this is why courses also have an `internal_course_number` property, which is maintained as a constant by the school. 

As such, fixing this issue will involve two steps:

- [ ] Based on the given `subject_prefix` and `course_number`, find the course's associated `internal_course_number`
- [ ] Aggregate based on the `internal_course_number` to ensure all versions of the course are properly included

**Comment by mikehquan19** [comment]
Hi @jpahm. I'm working on this task and found something weird. Apparently, in the test database, CS2340 and CS3340, despite being Computer Architecture, doesn't have the same ```internal_course_number```. CS2340's  ```internal_course_number``` is 015949 but CS3340's is 003490. I don't know if it's because the data in the database is different or something.

**Comment by jpahm** [comment]
This is an interesting case, as it seems to behave as expected for `ECS 2390` and `ECS 3390`. I guess the school decided that enough changes were made between `CS2340` and `CS3340` to warrant a new internal course number.

I would say a good fallback option here would be to defer to the given `catalog_year` to decide which to pull, or if no `catalog_year` is given, defer to whichever is the latest. Open to other ideas if you have them, though!

**Comment by jpahm** [comment]
Actually, I don't even think the grades endpoint takes a `catalog_year`, so probably just the latter method then.

**Comment by mikehquan19** [comment]
Hi @jpahm, I've managed to fix the course aggregation for ```grades``` endpoint so that it accounts for all the course with same ```internal_course_number```. However, I have a few questions. 

 -  For ```course``` endpoint, should I also change the functionality so that if the client queries ```subject_prefix``` and ```course_number```, it would return all the courses' versioning. For example, ```subject_prefix=ECS&course_number=3390``` would also return ```ECS 2390``` classes and vice-versa. 
 
-  For ```autocomplete``` endpoint, should I also do the same for ```course``` because I noticed that code also filters on ```courseCollection```? And what kind of data does the ```autocomplete``` endpoint serves as I don't see it in the docs ?

**Comment by jpahm** [comment]
Awesome, thanks for working on this! I wouldn't change the course endpoint since people can already query on `internal_course_number` if they want to; we don't want to return anything beyond what they actually query for.

I also wouldn't worry about doing anything with the `autocomplete` endpoint since it's currently being refactored to pull from the DAG view instead :)

As far as what data the `autocomplete` endpoint returns, it produces data in a format specifically designed for internal use with Trend's autocomplete generation, so it's not been very thoroughly documented yet. Essentially it just aggregates course and professor names underneath subjects and course numbers for building an autocomplete graph. I could make a separate issue for properly documenting this.

**Comment by mikehquan19** [comment]
Thank you for your feedback. I've created the pull request. Hope you will review it soon.

**Comment by jpahm** [comment]
> Thank you for your feedback. I've created the pull request. Hope you will review it soon.

Thanks! I'll review it shortly.

**Comment by jpahm** [comment]
Closed via #231
