### ISSUE TITLE
Aggregating Data for Athena

### ISSUE THREAD

**Issue by CharlieMahana** [UTDNebula/nebula-api#81]
We've already spoken about the sort of data that Athena needs aggregated by the API several times in relatively vague terms such as course and professor aggregations, however, we need a definite list of requirements so that we can ensure that everything is covered before launch. @eboysen could you please list the exact data aggregations you need for MVP?

**Comment by eboysen** [comment]
So as Charlie said, I think that we've talked about most of this in broad strokes as of yet. So I'll do my best to clarify what we are hoping to have by MVP. As of right now, the only data that we are in possession of is grade data. So all aggregations will be surrounding that, however, a lot of the points that I make here will also carry over once we get to professor evaluations, since we will likely want to display similar types of data to people.

As far as levels of aggregation we would like to see, there are 5 main points of entry that we would like to cover: sections, courses, course-professors combos, professors, and subjects. As of right now, sections is the only data that is being displayed for UTD Grades, the hope is that by aggregating data upwards we can give students a better view of what matters. A section is a specific instance ( CS 1337.001 21f Jason Smith). This is such a small data point, that it may not be very helpful in getting a bigger picture. So the next level up in specificity would be a course-professor combo. The example of this would be CS 1337 Jason Smith where the data being aggregated is every section of 1337 that Jason Smith has taught at UTD. A level above this would be courses (CS 1337) which would allow students to see an aggregate of all grades for every section of CS 1337 taught by any professor. Adjacent to this in the hierarchy would be professors (Jason Smith) which would include all the grades for any section of any course that Jason Smith has ever taught. A final tier would be subject (CS) which includes all sections of all courses taught by all professors that have that prefix. These entry points would allow questions to be answered like: how hard is this course regardless of professor, how hard is this professor across all subjects, how does this professor compare to the average professor in this course, etc. 

Beyond the basic aggregation (totaling the counts for all of the sections that fit into a category), the only other specific data point that we are hoping to have access to from the API is a metric to show data change over time. Sections obviously don't allow for such a thing, but something like a course, professor, course-professor, or subject, can be tracked over time. Essentially what were looking for here is a count of grades for each semester sent back to us in an ordered array of JSON in a similar format to this:
[
 {
      "semester": "21f",
      "average_GP": 3.5
  },
....
]
The average_GP attribute would be the average grade point for that semester. The hope here would be to allow students to observe trends in professor, department, or course performance over time. Has a professor's grades been improving, etc.

I hope that helps clarify any unclear aspects of what we are hoping to get from the API, if anyone has further follow up, please let me know and I'll do my best to get back quickly since we're all running on a tight schedule.

**Comment by AdamMcAdamson** [comment]
What is the desired timeline for this? Me having this done by 3/21 is unlikely, but by EOD 3/23 is realistic.
